version: '3.11'

services:
  bot:
    build: .
    container_name: ${SERVICE_NAME}
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["/bin/sh", "-c", "./script/run.sh"]
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  celery_worker:
    build: .
    command: celery -A app.bot.services.external.celery.tasks worker --loglevel=info --concurrency=1 --queues=example_queue

  celery_beat:
    build: .
    command: celery -A app.bot.services.external.celery.tasks beat -l INFO

volumes:
  db_data:
  redis_data:
